SRC = main.cpp Fixed.cpp

OBJ = $(SRC:.cpp=.o)
NAME = fixed
CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98

all : $(NAME)
$(NAME): $(OBJ)
	$(CXX) $(CXXFLAGS) $(OBJ) -o $(NAME) 
clean :
	rm -rf $(OBJ)

fclean : clean
	rm -rf $(NAME)
re :
	fclean all
.PHONY : all clean fclean re